export const copy = {
  it: {
    nav: {
      park: "Il park",
      rental: "Noleggio",
      races: "Gare",
      gallery: "Galleria",
      location: "Dove siamo",
      book: "Prenota & Ride",
      menu: "Apri menu",
      close: "Chiudi",
      language: "Lingua",
      skip: "Vai al contenuto",
    },
    hero: {
      line1: "DIVENTA",
      line2: "PROTAGONISTA.",
      sub: "Motocross, enduro e minicross a Ginosa. La tua prossima giornata in pista comincia qui.",
      rental: "Noleggia una moto",
      location: "GINOSA (TA), PUGLIA",
      scroll: "Scopri il park",
      skip: "Salta intro",
    },
    park: {
      title: "TRE MODI DI\nALZARE LA POLVERE.",
      intro: "Scegli la tua linea. Al resto pensa la voglia di girare.",
      mx: "Terra, gas e traiettorie. La tua pista motocross in Puglia.",
      enduro: "Esci dagli schemi. Trova il tuo ritmo sul fettucciato enduro.",
      mini: "La passione comincia da piccoli. Minicross a Ginosa, in provincia di Taranto.",
      discover: "Vieni a girare",
    },
    rental: {
      kicker: "NOLEGGIO ATTIVO",
      line1: "TU PORTA",
      line2: "LA VOGLIA.",
      title: "NON HAI LA MOTO?",
      text: "Nessun problema. Il noleggio moto cross è attivo. Scrivici per disponibilità, moto e attrezzatura: organizziamo insieme la tua giornata.",
      cta: "Noleggia una moto",
      details:
        "Moto, prezzi e attrezzatura? Chiedici tutti i dettagli prima di partire.",
    },
    booking: {
      title: "IL PROSSIMO GIRO\nINIZIA QUI.",
      text: "Due dettagli e sei pronto a scriverci. La prenotazione sarà confermata dal team.",
      name: "Nome",
      phone: "Telefono",
      date: "Data",
      category: "Categoria",
      rental: "Ti serve una moto?",
      people: "Numero di persone",
      message: "Il tuo messaggio",
      optional: "facoltativo",
      yes: "Sì, a noleggio",
      no: "No, ho la mia",
      submit: "Continua su WhatsApp",
      email: "Preferisci e-mail?",
      privacy:
        "I dati rimangono nel tuo browser fino all’apertura di WhatsApp o dell’app e-mail.",
      policy: "Leggi la privacy policy",
      error: "Controlla i campi evidenziati.",
      required: "Compila questo campo.",
      invalidPhone: "Inserisci un numero valido, con prefisso.",
      invalidDate: "Scegli oggi o una data futura.",
      invalidPeople: "Inserisci un numero intero maggiore di zero.",
      ready:
        "Messaggio pronto. Invia su WhatsApp per richiedere la prenotazione.",
      reopen: "Apri WhatsApp",
      select: "Scegli la disciplina",
      unavailable: "Il browser non ha aperto WhatsApp? Usa il link qui sotto.",
    },
    races: {
      title: "DIETRO IL CANCELLETTO.\nDAVANTI A TUTTO.",
      intro: "Trofeo Sud Italia MX UISP. La passione del Sud si incontra qui.",
      empty: "LA PROSSIMA SFIDA?",
      emptyText:
        "Le nuove date saranno pubblicate qui. Segui i nostri social per gli aggiornamenti sulle gare.",
      social: "Segui la stagione",
      timing: "Live timing",
      categories: "IN GARA",
      archive: "IL 2024 IN PISTA",
      riders: "piloti nella tappa 2024",
      regions: "regioni, una passione",
      community: "Puglia, Calabria, Basilicata e Campania.",
    },
    gallery: {
      title: "TERRA. GAS.\nBEI MOMENTI.",
      intro: "L’energia del motocross, in una serie di immagini illustrative.",
      placeholder: "Le immagini del park arrivano presto.",
      open: "Apri immagine",
      next: "Successiva",
      previous: "Precedente",
      mediaPending: "Foto in arrivo",
      moments: "VITA IN PISTA",
      follow: "Intanto, ci trovi su Instagram",
    },
    team: {
      kicker: "ASD MASSAFRA MX",
      title: "CI SI VEDE\nIN PISTA.",
      text: "Dalle prime traiettorie alla griglia di partenza. La ASD Massafra MX, presieduta da Francesco Laera, unisce chi vive il motocross con passione. Vieni a trovarci e diventa protagonista!",
      cta: "Conosci la community",
    },
    location: {
      title: "IL TUO PROSSIMO\nPUNTO DI PARTENZA.",
      text: "La nostra casa è a Ginosa, in Puglia. Imposta la destinazione e vieni a trovarci.",
      directions: "Indicazioni",
      loadMap: "Carica la mappa",
      mapNotice:
        "La mappa viene fornita da Google e si carica solo se lo scegli.",
      open: "Aperti tutti i giorni",
      contact:
        "Prima di partire, controlla il meteo e gli aggiornamenti sui social.",
    },
    footer: {
      title: "CI VEDIAMO\nAL CANCELLETTO.",
      contact: "PARLIAMONE",
      social: "SEGUI LA POLVERE",
      legal: "Dati societari e P.IVA: TODO_CLIENTE",
      rights: "Massafra MX Park. Ginosa (TA), Italia.",
      privacy: "Privacy policy",
      cookies: "Cookie policy",
      motion: "Pausa animazioni",
      resume: "Attiva animazioni",
      top: "Torna su",
    },
  },
  en: {
    nav: {
      park: "The park",
      rental: "Bike rental",
      races: "Races",
      gallery: "Gallery",
      location: "Find us",
      book: "Book & Ride",
      menu: "Open menu",
      close: "Close",
      language: "Language",
      skip: "Skip to content",
    },
    hero: {
      line1: "BE THE",
      line2: "MAIN EVENT.",
      sub: "Motocross, enduro and minicross in Ginosa, Puglia. Your next day on track starts here.",
      rental: "Rent a bike",
      location: "GINOSA (TA), PUGLIA",
      scroll: "Explore the park",
      skip: "Skip intro",
    },
    park: {
      title: "THREE WAYS TO\nKICK UP THE DIRT.",
      intro: "Choose your line. Bring your appetite for riding.",
      mx: "Dirt, throttle and corners. Your motocross track in Puglia.",
      enduro: "Find your own rhythm on our marked enduro course.",
      mini: "Big passion starts small. Minicross in Ginosa, in the province of Taranto.",
      discover: "Come ride",
    },
    rental: {
      kicker: "BIKE RENTAL AVAILABLE",
      line1: "BRING YOUR",
      line2: "APPETITE.",
      title: "NO BIKE?",
      text: "No problem. Bike rental is available. Message us about availability, bikes and equipment, and let’s plan your day on track.",
      cta: "Rent a bike",
      details:
        "Bikes, prices and equipment? Get the details before you set off.",
    },
    booking: {
      title: "YOUR NEXT RIDE\nSTARTS HERE.",
      text: "A few details and you’re ready to message us. Your booking will be confirmed by the team.",
      name: "Name",
      phone: "Phone",
      date: "Date",
      category: "Category",
      rental: "Need a bike?",
      people: "Number of people",
      message: "Your message",
      optional: "optional",
      yes: "Yes, a rental",
      no: "No, I have my own",
      submit: "Continue on WhatsApp",
      email: "Prefer email?",
      privacy:
        "Your details stay in your browser until you open WhatsApp or your email app.",
      policy: "Read the privacy policy",
      error: "Check the highlighted fields.",
      required: "Please complete this field.",
      invalidPhone: "Enter a valid phone number, including country code.",
      invalidDate: "Choose today or a future date.",
      invalidPeople: "Enter a whole number greater than zero.",
      ready: "Message ready. Send it on WhatsApp to request your booking.",
      reopen: "Open WhatsApp",
      select: "Choose a discipline",
      unavailable: "WhatsApp did not open? Use the link below.",
    },
    races: {
      title: "BEHIND THE GATE.\nAHEAD OF IT ALL.",
      intro:
        "Trofeo Sud Italia MX UISP. Southern Italy’s riding community meets here.",
      empty: "THE NEXT CHALLENGE?",
      emptyText:
        "New dates will appear here. Follow our social channels for race updates.",
      social: "Follow the season",
      timing: "Live timing",
      categories: "ON THE GRID",
      archive: "THE 2024 ROUND",
      riders: "riders at the 2024 round",
      regions: "regions, one passion",
      community: "Puglia, Calabria, Basilicata and Campania.",
    },
    gallery: {
      title: "DIRT. THROTTLE.\nGOOD TIMES.",
      intro: "The energy of motocross, in a series of illustrative images.",
      placeholder: "Photos from the park are coming soon.",
      open: "Open image",
      next: "Next",
      previous: "Previous",
      mediaPending: "Photos coming soon",
      moments: "TRACK LIFE",
      follow: "Until then, find us on Instagram",
    },
    team: {
      kicker: "ASD MASSAFRA MX",
      title: "SEE YOU\nON TRACK.",
      text: "From first corners to the starting gate. Led by Francesco Laera, ASD Massafra MX brings together people who live for motocross. Come see us and make it your day on track.",
      cta: "Meet the community",
    },
    location: {
      title: "YOUR NEXT\nSTARTING POINT.",
      text: "Our home is Ginosa, Puglia. Set your destination and come ride with us.",
      directions: "Get directions",
      loadMap: "Load the map",
      mapNotice:
        "The map is provided by Google and only loads when you choose.",
      open: "Open every day",
      contact: "Before travelling, check the weather and our social updates.",
    },
    footer: {
      title: "SEE YOU AT\nTHE GATE.",
      contact: "LET’S TALK",
      social: "FOLLOW THE DIRT",
      legal: "Legal entity and VAT number: TODO_CLIENTE",
      rights: "Massafra MX Park. Ginosa (TA), Italy.",
      privacy: "Privacy policy",
      cookies: "Cookie policy",
      motion: "Pause animations",
      resume: "Enable animations",
      top: "Back to top",
    },
  },
} as const;
export type Copy = (typeof copy)["it"] | (typeof copy)["en"];
